import { ArrowLeft, ArrowRight, FolderTree, Search } from "lucide-react";
import { Link } from "wouter";
import SiteNav from "@/components/SiteNav";
import { trpc } from "@/lib/trpc";

export default function Category({ params }: { params: { slug: string } }) {
  const categories = trpc.marketplace.categories.useQuery();
  const products = trpc.marketplace.list.useQuery({ category: params.slug });
  const category = categories.data?.find((item) => item.slug === params.slug);
  return <div className="numi-shell min-h-screen bg-[#06111f]"><div className="numi-content"><SiteNav /><main className="mx-auto max-w-[1440px] px-5 pb-24 md:px-10"><Link href="/#collection" className="mb-12 inline-flex items-center gap-2 text-xs uppercase tracking-[.18em] text-white/45 hover:text-white"><ArrowLeft size={14} /> Back to showroom</Link><section className="relative overflow-hidden rounded-[36px] border border-white/10 bg-[#0a1b2d]/80 p-8 md:p-16"><div className="pattern-star absolute right-12 top-10 h-44 w-44 opacity-25" /><div className="relative max-w-3xl"><div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.24em] text-[#ef8b65]"><FolderTree size={14} /> Category / {params.slug}</div><h1 className="mt-7 text-6xl font-semibold tracking-[-.08em] text-white md:text-8xl">{category?.name ?? "Category"}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/55">{category?.description ?? "A curated slice of the NUMI digital showroom."}</p><div className="mt-8 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-white/35"><Search size={14} /> {products.data?.length ?? 0} published systems</div></div></section><section className="mt-12">{products.isLoading ? <div className="h-72 animate-pulse rounded-[28px] bg-white/5" /> : products.data?.length ? <div className="grid gap-6 md:grid-cols-3">{products.data.map(({ product, techStack }) => <article key={product.id} className="product-card glass overflow-hidden rounded-[28px]"><img src={product.heroImage} alt={`${product.name} preview`} className="aspect-[1.18] w-full object-cover" /><div className="space-y-4 p-6"><h2 className="text-2xl font-semibold text-white">{product.name}</h2><p className="text-sm leading-6 text-white/50">{product.tagline}</p><div className="flex flex-wrap gap-2">{techStack.slice(0, 3).map((stack) => <span key={stack.name} className="rounded-full bg-white/[.06] px-2.5 py-1 font-mono text-[10px] text-white/50">{stack.name}</span>)}</div><Link href={`/websites/${product.slug}`} className="flex items-center gap-2 text-sm font-semibold text-[#83c2ff]">Inspect system <ArrowRight size={15} /></Link></div></article>)}</div> : <div className="glass rounded-[28px] p-10 text-center text-white/55">No published systems in this category yet.</div>}</section></main></div></div>;
}
