import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Chrome, Loader2, Mail, Lock, UserPlus } from "lucide-react";
import { Link, useLocation } from "wouter";
import { supabase } from "@/lib/supabase";
export default function Login() {
 const [,navigate]=useLocation(); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session) navigate("/account")})},[navigate]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");const r=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/account"}});setBusy(false);if(r.error){setMessage(r.error.message);return}if(mode==="signup"&&!r.data.session){setMessage("Check your email to confirm your account, then sign in.");return}navigate("/account")};
 const google=async()=>{setBusy(true);setMessage("");const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/account"}});if(error){setBusy(false);setMessage(error.message)}};
 return <main className="min-h-screen bg-[#040b16] px-5 py-10 text-white"><div className="mx-auto flex min-h-[85vh] max-w-md items-center justify-center"><section className="w-full rounded-[28px] border border-white/10 bg-white/[0.04] p-7 shadow-2xl backdrop-blur-xl"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={15}/> Back to NUMI</Link><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#83c2ff]">NUMI / CUSTOMER ACCESS</p><h1 className="mt-2 text-3xl font-semibold">{mode==="signin"?"Welcome back":"Create your account"}</h1><p className="mt-2 text-sm text-white/50">Customer login only. Owner controls are completely separate.</p><button type="button" disabled={busy} onClick={google} className="mt-7 flex w-full items-center justify-center gap-3 rounded-full border border-white/15 bg-white/[0.06] px-4 py-3 text-sm font-semibold hover:bg-white/[0.1]"><Chrome size={17}/> Continue with Google</button><div className="my-6 flex items-center gap-3 text-xs text-white/30"><span className="h-px flex-1 bg-white/10"/>OR<span className="h-px flex-1 bg-white/10"/></div><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-2 block text-xs text-white/55">Email</span><div className="relative"><Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-white/30" size={16}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/20 py-3 pl-10 pr-4 text-sm outline-none"/></div></label><label className="block"><span className="mb-2 block text-xs text-white/55">Password</span><div className="relative"><Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-white/30" size={16}/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/20 py-3 pl-10 pr-4 text-sm outline-none"/></div></label>{message&&<p className="rounded-2xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-xs text-amber-200">{message}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-full bg-[#3b8bff] px-4 py-3 text-sm font-semibold disabled:opacity-50">{busy?<Loader2 size={16} className="animate-spin"/>:<UserPlus size={16}/>} {mode==="signin"?"Sign in":"Create account"}</button></form><button type="button" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}} className="mt-5 w-full text-center text-xs text-white/45 hover:text-white">{mode==="signin"?"New customer? Create an account":"Already have an account? Sign in"}</button></section></div></main>;
}
