/**
 * NUMI Boutique — seed catalog
 * Personal store for ready-made websites. Replace with your real products in Admin.
 */
export const catalogSeed = [
  {
    slug: "dar-restaurant",
    name: "Dar Restaurant",
    tagline: "موقع أنيق للمطاعم والكافيهات.",
    description:
      "نظام موقع جاهز للمطاعم: قائمة طعام، حجوزات، معرض صور، ومعلومات الاتصال. مناسب للإطلاق السريع مع هوية محلية واضحة.",
    category: "Restaurants & Cafés",
    price: "45000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-atlas.svg",
    demoUrl: null,
    requirements: "اسم المطعم، شعار، صور الأطباق، رقم واتساب، وعنوان.",
    license: "رخصة مشروع واحد تجارية. استخدام لمطعم أو فرع واحد.",
    included: "الكود المصدري، تصميم متجاوب، صفحات القائمة والحجز، دليل التسليم، دعم إطلاق أساسي.",
    faq: "س: هل الموقع جاهز للنشر؟\nج: نعم كأساس جاهز. تضيف محتواك (صور، قائمة، تواصل) ثم ننشره.\n\nس: هل يمكن التعديل؟\nج: نعم. تحصل على المصدر ويمكن تخصيص الألوان والنصوص.\n\nس: ما الرخصة؟\nج: رخصة مشروع واحد لمطعمك.",
    seoTitle: "Dar Restaurant — موقع مطعم جاهز",
    seoDescription: "موقع مطعم جاهز للإطلاق مع قائمة وحجوزات وتصميم متجاوب.",
    features: [
      ["قائمة طعام واضحة", "عرض الأطباق والأسعار بطريقة مرتبة وسهلة القراءة."],
      ["حجز سريع", "قسم حجوزات وربط واتساب للزبائن."],
      ["جاهز للموبايل", "تصميم يعمل جيداً على الهاتف أولاً."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    slug: "salon-lumiere",
    name: "Salon Lumière",
    tagline: "واجهة فاخرة لصالونات التجميل والحلاقة.",
    description:
      "موقع لصالون تجميل أو حلاقة: خدمات، أسعار، معرض أعمال، وحجز مواعيد. يعطي انطباعاً احترافياً من أول زيارة.",
    category: "Beauty & Salon",
    price: "38000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-mono.svg",
    demoUrl: null,
    requirements: "اسم الصالون، الخدمات، الأسعار التقريبية، صور الأعمال، رقم الحجز.",
    license: "رخصة مشروع واحد تجارية لصالون واحد.",
    included: "المصدر، صفحات الخدمات والمعرض، نموذج تواصل، دليل إطلاق.",
    faq: "س: هل يناسب الرجال والنساء؟\nج: نعم، يمكن تكييف النصوص والصور بسهولة.\n\nس: هل فيه حجز مواعيد؟\nج: قسم مخصص + ربط واتساب كبداية عملية.",
    seoTitle: "Salon Lumière — موقع صالون جاهز",
    seoDescription: "موقع جاهز لصالونات التجميل والحلاقة مع خدمات ومعرض.",
    features: [
      ["عرض الخدمات", "قائمة خدمات وأسعار مرتبة."],
      ["معرض أعمال", "صالة صور تعكس جودة الشغل."],
      ["تواصل سريع", "أزرار واتساب واتصال واضحة."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    slug: "folio-pro",
    name: "Folio Pro",
    tagline: "بورتفوليو نظيف للمستقلين والمبدعين.",
    description:
      "موقع شخصي لعرض أعمالك: مشاريع، نبذة، خدمات، وصفحة تواصل. مثالي للمصمم، المطور، المصور، أو أي مستقل يريد حضوراً احترافياً.",
    category: "Portfolio",
    price: "28000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-signal.svg",
    demoUrl: null,
    requirements: "صور أعمالك، نبذة قصيرة، روابط تواصل، قائمة خدمات إن وجدت.",
    license: "رخصة مشروع واحد شخصية/تجارية لصاحب البورتفوليو.",
    included: "المصدر، شبكة مشاريع، صفحة عنّي، تواصل، دليل نشر.",
    faq: "س: هل أقدر نضيف مشاريع لاحقاً؟\nج: نعم، البنية جاهزة لإضافة أعمال جديدة.\n\nس: هل مناسب للمبتدئين؟\nج: نعم، بسيط وواضح بدون تعقيد.",
    seoTitle: "Folio Pro — بورتفوليو جاهز",
    seoDescription: "بورتفوليو احترافي للمستقلين لعرض المشاريع والخدمات.",
    features: [
      ["شبكة مشاريع", "عرض أعمالك بطريقة مرتبة وجذابة."],
      ["صفحة خدمات", "اشرح ماذا تقدم وبأي طريقة."],
      ["تواصل مباشر", "نموذج ووسائل تواصل واضحة."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    slug: "local-services",
    name: "Local Services",
    tagline: "موقع شركات الخدمات المحلية.",
    description:
      "نظام لمقاول، سباكة، كهرباء، نقل، أو أي خدمة محلية: خدمات، مناطق التغطية، شهادات، وطلب خدمة سريع عبر واتساب.",
    category: "Local Business",
    price: "32000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-atlas.svg",
    demoUrl: null,
    requirements: "اسم الشركة، الخدمات، المدن التي تغطيها، رقم واتساب، صور إن وجدت.",
    license: "رخصة مشروع واحد لنشاط خدمات واحد.",
    included: "المصدر، صفحات الخدمات والمناطق، CTA واضح، دليل تسليم.",
    faq: "س: هل يخدم عدة ولايات؟\nج: نعم، يمكن ذكر مناطق التغطية في المحتوى.\n\nس: الأهم للزبون؟\nج: وضوح الخدمة وزر تواصل سريع.",
    seoTitle: "Local Services — موقع خدمات محلية",
    seoDescription: "موقع جاهز لمقدّمي الخدمات المحلية مع طلب سريع.",
    features: [
      ["خدمات واضحة", "كل خدمة مشروحة باختصار."],
      ["طلب سريع", "زر واتساب/اتصال بارز."],
      ["ثقة محلية", "مساحة للشهادات وأعمال سابقة."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    slug: "immo-vue",
    name: "Immo Vue",
    tagline: "واجهة عقارية لعرض الشقق والعقارات.",
    description:
      "موقع للوكلاء العقاريين أو أصحاب المشاريع: بطاقات عقارات، فلترة بسيطة، وتفاصيل كل عقار مع تواصل مباشر.",
    category: "Real Estate",
    price: "52000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-mono.svg",
    demoUrl: null,
    requirements: "قائمة عقارات أولية، صور، أسعار أو مجالات سعر، معلومات الوكيل.",
    license: "رخصة مشروع واحد لنشاط عقاري واحد.",
    included: "المصدر، شبكة عقارات، صفحة تفاصيل، تواصل، دليل إطلاق.",
    faq: "س: كم عقار أقدر نعرض؟\nج: البنية تدعم قائمة متنامية؛ البداية بعدد صغير كافية.\n\nس: هل فيه بحث؟\nج: فلترة أساسية حسب النوع/المدينة قابلة للتوسيع.",
    seoTitle: "Immo Vue — موقع عقاري جاهز",
    seoDescription: "موقع لعرض العقارات مع بطاقات وتفاصيل وتواصل.",
    features: [
      ["بطاقات عقارات", "عرض مرتب للشقق والأراضي والمشاريع."],
      ["تفاصيل واضحة", "صفحة لكل عقار مع الصور والمعلومات."],
      ["تواصل الوكيل", "زر مباشر للجادّين من الزبائن."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    slug: "boutique-lite",
    name: "Boutique Lite",
    tagline: "واجهة خفيفة لمتجر منتجات بسيط.",
    description:
      "موقع لمتجر صغير أو براند محلي: عرض منتجات، تصنيفات بسيطة، وطلب عبر واتساب بدون تعقيد متجر إلكتروني كامل.",
    category: "Shop",
    price: "42000.00",
    currency: "DZD",
    status: "published" as const,
    heroImage: "/assets/product-signal.svg",
    demoUrl: null,
    requirements: "قائمة منتجات، صور، أسعار، طريقة الطلب (واتساب/هاتف).",
    license: "رخصة مشروع واحد لمتجر واحد.",
    included: "المصدر، شبكة منتجات، صفحة منتج، طلب واتساب، دليل إطلاق.",
    faq: "س: هل فيه دفع داخل الموقع؟\nج: النسخة الأساسية تعتمد الطلب عبر واتساب. يمكن إضافة بوابة لاحقاً.\n\nس: مناسب للمنتجات اليدوية؟\nج: نعم جداً.",
    seoTitle: "Boutique Lite — واجهة متجر بسيطة",
    seoDescription: "موقع متجر خفيف لعرض المنتجات والطلب عبر واتساب.",
    features: [
      ["عرض منتجات", "شبكة نظيفة للمنتجات والتصنيفات."],
      ["طلب واتساب", "الزبون يطلب مباشرة بدون تعقيد."],
      ["هوية البراند", "مساحة للقصة والصور القوية."],
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
] as const;

export const categorySeed = [
  {
    slug: "restaurants-cafes",
    name: "Restaurants & Cafés",
    description: "مواقع للمطاعم والكافيهات مع قائمة وحجوزات.",
    sortOrder: 10,
  },
  {
    slug: "beauty-salon",
    name: "Beauty & Salon",
    description: "صالونات تجميل وحلاقة وخدمات العناية.",
    sortOrder: 20,
  },
  {
    slug: "portfolio",
    name: "Portfolio",
    description: "بورتفوليو للمستقلين والمبدعين.",
    sortOrder: 30,
  },
  {
    slug: "local-business",
    name: "Local Business",
    description: "شركات وخدمات محلية تحتاج حضوراً واضحاً.",
    sortOrder: 40,
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    description: "عرض عقارات ومشاريع سكنية.",
    sortOrder: 50,
  },
  {
    slug: "shop",
    name: "Shop",
    description: "واجهات متاجر ومنتجات بطلب بسيط.",
    sortOrder: 60,
  },
] as const;
